
import type { ProductTemplate, ChecklistItem } from './types';

export const parametrosChecklist: ChecklistItem[] = [
    {id: 1, nombre: 'verticalidad', pregunta: '¿La estiba mantiene la verticalidad?', descripcion: 'Verificar que las botellas mantengan posición vertical (tolerancia: ≤ 0.3 mm)'},
    {id: 2, nombre: 'factor_estiba', pregunta: '¿Cumple con el factor de estiba?', descripcion: 'Altura total / altura referencia ≤ factor máximo'},
    {id: 3, nombre: 'tarima_estado', pregunta: '¿La tarima está en buen estado?', descripcion: 'Sin daños, superficie plana, limpia, sin astillas'},
    {id: 4, nombre: 'producto_integro', pregunta: '¿El producto y empaque están íntegros?', descripcion: 'Botellas sin deformaciones, etiquetas adheridas, empaques sin roturas'},
    {id: 5, nombre: 'perpendicularidad', pregunta: '¿Perpendicularidad de botellas individuales es correcta?', descripcion: 'Medición con instrumento calibrado (≤ 0.3 mm desviación)'},
    {id: 6, nombre: 'alineacion_capas', pregunta: '¿Alineación de capas en la estiba es correcta?', descripcion: 'Cajas alineadas verticalmente, sin desplazamientos laterales'},
    {id: 7, nombre: 'estabilidad_lateral', pregunta: '¿La estiba tiene estabilidad al empuje lateral?', descripcion: 'Resistencia a fuerzas laterales, mantiene verticalidad'},
    {id: 8, nombre: 'altura_uniforme', pregunta: '¿La altura de la estiba es uniforme?', descripcion: 'Variación máxima entre puntos ≤ 5 mm'},
    {id: 9, nombre: 'film_condition', pregunta: '¿Film retráctil/flejado en buena condición?', descripcion: 'Tensión adecuada, sin roturas, cobertura completa'},
    {id: 10, nombre: 'ubicacion_correcta', pregunta: '¿Ubicación correcta en almacén?', descripcion: 'Posición adecuada según procedimientos de almacenamiento'}
];

export const productTemplates: ProductTemplate[] = [
    {sku: "360", descripcion: "COCA  COLA 600 ML 24 PK", factorEstiba: "2.5"},
    {sku: "376", descripcion: "CC PET 2L NO RET 8 PK", factorEstiba: "2.5"},
    {sku: "396", descripcion: "COCA LIGHT 2 LT PET NR 8 C", factorEstiba: "2.5"},
    {sku: "445", descripcion: "COCA COLA 3 LT PET NR 4 PK", factorEstiba: "2.5"},
    {sku: "500", descripcion: "CC 2.5L NO RET 8 PACK", factorEstiba: "2.5"},
    {sku: "501", descripcion: "COCA COLA 2.5 LT REF-PET 8 CJ", factorEstiba: "3.0"},
    {sku: "610", descripcion: "COCA COLA 600ML PETNR 12PK", factorEstiba: "2.0"},
    {sku: "614", descripcion: "FRESCA 2L PET NR 8PK", factorEstiba: "2.5"},
    {sku: "615", descripcion: "FRESCA 600ML PET NR 24PK", factorEstiba: "2.5"},
    {sku: "640", descripcion: "SIDRAL MUNDET 600ML NR", factorEstiba: "2.5"},
    {sku: "641", descripcion: "SIDRAL MUNDET 2L NR 8PK", factorEstiba: "2.5"},
    {sku: "658", descripcion: "FANTA 600ML PET NR 24PK", factorEstiba: "2.5"},
    {sku: "665", descripcion: "FANTA 2L PET NR 8PK", factorEstiba: "2.5"},
    {sku: "674", descripcion: "SPRITE 600ML PET NR 24PK", factorEstiba: "2.5"},
    {sku: "675", descripcion: "SPRITE 2L PET NR 8PK", factorEstiba: "2.5"},
    {sku: "702", descripcion: "CC SIN AZUCAR 600ML NR 24PK", factorEstiba: "2.5"},
    {sku: "711", descripcion: "CC SIN AZUCAR 2L NR 8PK", factorEstiba: "2.5"},
    {sku: "854", descripcion: "DELAWARE PUNCH 600ML", factorEstiba: "2.5"},
    {sku: "872", descripcion: "TOPO CHICO SANGRIA 600", factorEstiba: "2.5"},
    {sku: "874", descripcion: "TOPO CHICO TORONJA 600", factorEstiba: "2.5"},
    {sku: "908", descripcion: "CIEL AGUA NAT 600ML 24PK", factorEstiba: "3.0"},
    {sku: "909", descripcion: "CIEL AGUA NAT 1L 12PK", factorEstiba: "3.0"},
    {sku: "910", descripcion: "CIEL AGUA NAT 1.5L 12PK", factorEstiba: "3.0"},
    {sku: "945", descripcion: "CIEL SAB JAMAICA 1L 12PK", factorEstiba: "3.0"},
    {sku: "946", descripcion: "CIEL SAB LIMON 1L 12PK", factorEstiba: "3.0"},
    {sku: "947", descripcion: "CIEL SAB MANDARINA 1L 12PK", factorEstiba: "3.0"},
    {sku: "983", descripcion: "POWERADE MORAS 500ML 24PK", factorEstiba: "2.5"},
    {sku: "984", descripcion: "POWERADE LIMA LIMON 500ML 24PK", factorEstiba: "2.5"},
    {sku: "986", descripcion: "POWERADE UVA 500ML 24PK", factorEstiba: "2.5"},
    {sku: "987", descripcion: "POWERADE NARANJA 500ML 24PK", factorEstiba: "2.5"},
    {sku: "989", descripcion: "POWERADE MORAS 1L 12PK", factorEstiba: "2.5"},
    {sku: "990", descripcion: "POWERADE UVA 1L 12PK", factorEstiba: "2.5"},
    {sku: "992", descripcion: "POWERADE NARANJA 1L 12PK", factorEstiba: "2.5"},
    {sku: "994", descripcion: "POWERADE LIMA LIMON 1L 12PK", factorEstiba: "2.5"},
    {sku: "1119", descripcion: "COCA COLA 1.75 ML PET NR 8 PACK", factorEstiba: "2.0"},
    {sku: "1511", descripcion: "VITAMIN WATER XXX 500ML 24P", factorEstiba: "2.5"},
    {sku: "1512", descripcion: "VITAMIN WATER POWER-C 500ML 24P", factorEstiba: "2.5"},
    {sku: "1513", descripcion: "VITAMIN WATER ENERGY 500ML 24P", factorEstiba: "2.5"},
    {sku: "1514", descripcion: "VITAMIN WATER FOCUS 500ML 24P", factorEstiba: "2.5"},
    {sku: "1515", descripcion: "VITAMIN WATER ESSENTIAL 500ML 24P", factorEstiba: "2.5"},
    {sku: "1516", descripcion: "VITAMIN WATER RESTORE 500ML 24P", factorEstiba: "2.5"},
    {sku: "2352", descripcion: "CC COLA BOT 3L RET PET 6p", factorEstiba: "3.0"},
    {sku: "2898", descripcion: "Coca Cola SA 2.5 LT REF PET 8PK", factorEstiba: "2.5"},
    {sku: "2908", descripcion: "COCA-COLA 2.25L PNR 8 pk", factorEstiba: "2.0"},
    {sku: "2909", descripcion: "COCA-COLA 1.35L PET NR 12 pk", factorEstiba: "2.0"},
    {sku: "3019", descripcion: "Coca Cola Original 2.75L $35 4pk", factorEstiba: "2.0"},
    {sku: "3276", descripcion: "CC COLA BOT 3L RET PET 6p Preciada", factorEstiba: "3.0"},
    {sku: "99938", descripcion: "FANTA NARANJA 2.5 LT REF PET 8PK", factorEstiba: "3.0"},
    {sku: "99939", descripcion: "SIDRAL MUNDET 2.5 LT REF PET 8PK", factorEstiba: "3.0"},
    {sku: "99940", descripcion: "FRESCA 2.5 LT REF PET 8PK", factorEstiba: "3.0"}
];
